config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'top' => 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books do
    resource :likes, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :book_commentss, dependent: :destroy
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    @book_comment.save
    
  end
  
  def destroy
     @book = Book.find(params[:book_id])
     book_comment = @book.book_comments.find(params[:id])
     book_comment.destroy
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:content)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
    
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    like = @book.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    like = @book.likes.find_by(user_id: current_user.id)
    like.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book-comment.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user) do %>
        <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg", size: "50x50" %>
        <br><%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.content %></td>
    <% if book_comment.user == current_user %>
    <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: "btn btn-sm btn-danger", method: :delete, remote: true %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/book_comments/_comment-form.html.erb
<%= form_with(model: [book,book_comment]) do |f| %>
<%= f.text_area :content, id: "comment-form", size: "80x5" %><br>
<%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
$("#comments-area").html("<%= j(render 'book_comments/book-comment', book: @book, book_comment: @book_comment) %>");
$("#comment-form").val('');

app/views/book_comments/destroy.js.erb
$("#comments-area").html("<%= j(render 'book_comments/book-comment', book: @book, book_comment: @book_comment) %>");

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= @book.errors.count %>error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
           <% end %>
        </ul>
      </div>
      <% end %>

      <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label class="book_title">Title</label>
          <br>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label class="book_opinin">Opinion</label>
          <br>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      <text>|</text>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= @book.errors.count %>error prohibited this obj from being saved:
    </h3>
    <ul>
      <li>
        <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      </li>
    </ul>
  </diV>
        <% end %>
  <% end %>
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
            <td id="like-btn-<%= book.id %>"><%= render "likes/like-btn", book: book %></td>
            <td><p>コメント:<%= book.book_comments.count %></p></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <%= render 'users/list', user: @user, book: @book_new %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %><br>
                            <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td><%= link_to @book.title, book_path(@book.id) %></td>
                        <td><%= @book.body %></td>
                         <td id="like-btn-<%= @book.id %>"><%= render "likes/like-btn", book: @book %></td>

                        <td>
                            <% if @user.id == current_user.id %>
                                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                            <% end %>
                        </td>
                        <td>
                            <% if @user.id == current_user.id %>
                                <%= link_to "Destroy", @book, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div id="comments-area"><%= render 'book_comments/book-comment', book: @book, book_comment: @book_comment %></div>
            <%= render 'book_comments/comment-form', book: @book, book_comment: @book_comment %>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
          <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %></li>
                <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
                <li><%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %></li>
                <li><%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
                <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
                <li><%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id="notice">
        <%= notice %>
        </p>
      <%= yield %>
    </main>

  </body>
  <footer>
    <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
    </div>
  </footer>
</html>

app/views/likes/_like-btn.html.erb
<% if book.liked_by?(current_user) %>
  <%= link_to book.likes.count, book_likes_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.likes.count, book_likes_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/likes/create.js.erb
$("#like-btn-<%= @book.id %>").html("<%= j(render "likes/like-btn", book: @book) %>");

app/views/likes/destroy.js.erb
$("#like-btn-<%= @book.id %>").html("<%= j(render "likes/like-btn", book: @book) %>");

app/views/users/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>

      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion",class>Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3>
          <%= @user.errors.count %>error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
           <% end %>
        </ul>
      </div>
      <% end %>

      <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <label class="user_name">Name</label>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label class="user_intrduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
      <%= render 'users/list', user: @user, book: @book %>
      <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
              <thead>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                  </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>
                  <tr>
                      <td>
                          <%= link_to user_path(book.user.id) do %>
                          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
                          <% end %>
                      </td>
                      <td><%= link_to book.title, book_path(book.id) %></td>
                      <td><%= book.body %></td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
      </div>
  </div>
</div>